services:
  mysql-php-container:
    container_name: mysql-php-container
    image: mysql:8.2.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  php-container:
    container_name: php-container
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql-php-container

volumes:
  mysql_data: